site_name: MorphLab

site_description: Experimental Mechatronics Research Platform

repo_name: MahdiHooshmand/MorphLab

repo_url: https://github.com/MahdiHooshmand/MorphLab

theme:
  name: material

nav:

  - Home: index.md

  - RFC:
      - RFC-001: rfcs/RFC-001-Platform-Vision.md
      - RFC-002: rfcs/RFC-002-Terminology.md
      - RFC-003: rfcs/RFC-003-Domain-Model.md
      - RFC-004: rfcs/RFC-004-System-Context.md
      - RFC-005: rfcs/RFC-005-Design-Principles.md

  - ADR: adrs/

  - Standards: standards/

  - Specifications: specifications/

markdown_extensions:

  - admonition

  - toc:
      permalink: true

  - tables

  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.highlight

  - pymdownx.inlinehilite

  - pymdownx.tabbed

  - pymdownx.emoji
